---
- name: Install libselinux-python
  yum: name=libselinux-python state=present

- name: Change SELinux Policy Mode
  command: setenforce permissive
  ignore_errors: True

- name: Install Packeges
  yum: name={{ item }} state=present
  with_items:
    - epel-release
    - gcc
    - vim
    - git
    - curl
    - wget
    - zip
    - unzip
    - htop
    - iotop
    - postfix
    - ca-certificates
    - ImageMagick
