---
# --
- name: Install libselinux-python
  yum: name=libselinux-python state=present
# --

# --
- name: Change SELinux Policy Mode
  selinux: state=disabled
  ignore_errors: True
# --

# --
- name: upgrade all packages
  yum: name=* state=latest
# --

# --
- name: check remi-repo
  stat: path=/etc/yum.repos.d/remi.repo
  register: remi_repo
# --

# --
- block:
  - name: epel-release
    yum: name=epel-release state=installed

  when: not remi_repo.stat.exists
# --

# --
- name: Install Packeges
  yum: name={{ item }} state=present
  with_items:
    - ansible
    - gcc
    - vim
    - git
    - curl
    - wget
    - zip
    - unzip
    - htop
    - iotop
    - postfix
    - ca-certificates
    - ImageMagick
    - ruby
# --