---
- name: Install libselinux-python
  yum: name=libselinux-python state=present

- name: Change SELinux Policy Mode
  command: setenforce permissive
  ignore_errors: True

- name: epel-release
  yum: name=epel-release state=installed
  ignore_errors: True

- name: Add repository 'remi-repo'
  command: rpm -ih {{ remi_repo }} creates=/etc/yum.repos.d/remi.repo
  ignore_errors: True

- name: Install Packeges
  yum: name={{ item }} state=present
  with_items:
    - epel-release
    - gcc
    - vim
    - git
    - curl
    - wget
    - zip
    - unzip
    - htop
    - iotop
    - postfix
    - ca-certificates
    - ImageMagick
    - ruby