---
# --
- name: Install libselinux-python
  yum: name=libselinux-python state=present

- name: Change SELinux Policy Mode
  command: setenforce permissive
  ignore_errors: True

# --
- name: check remi-repo
  stat: path=/etc/yum.repos.d/remi.repo
  register: remi_repo
# --

# --
- block:
  - name: epel-release
    yum: name=epel-release state=installed

  - name: Add repository 'remi-repo'
    yum: {{ item }} state=present
    with_items:
      {{ remi_repos }}

  when: not remi_repo.stat.exists
# --

# --
- name: Install Packeges
  yum: name={{ item }} state=present
  with_items:
    - epel-release
    - gcc
    - vim
    - git
    - curl
    - wget
    - zip
    - unzip
    - htop
    - iotop
    - postfix
    - ca-certificates
    - ImageMagick
    - ruby
# --